version: "3.8"

services: 
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 7000:7000
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - net
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000 
    # volumes: 
    #   - .:/app
    #   - '/app/node_modules'
    depends_on: 
      - mysql_server
    networks:
      - net
  
  mysql_server:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    # container_name: mysql_server
    environment: 
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - net
networks:
      net: 

    